### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by IliaEremin** [BobZhao/OpenTerminalHere#3]
Hello!
I could not use OpenInTerminalHere plugin until I performed following setup:

![screen shot 2017-09-08 at 11 45 17 am](https://user-images.githubusercontent.com/1190759/30203626-4bc3ead4-948b-11e7-9189-4b81475aec19.png)

Could you please add this step in README.
I use AndroidStudio (based on intellij) on MacOS.

**Comment by duckbyte** [comment]
Are you sure that was for this plugin? I don't have that (and the names don't match) and I don't see anything in the code corresponding to this configuration

**Comment by mx1up** [comment]
yes, it's there, but I also don't find it in the code, i think @BobZhao maybe forgot to commit this?
I installed through the intellij plugin repo: https://plugins.jetbrains.com/plugin/8081-open-terminal-here

Also, looking at the code, this plugin would not work under linux (no executor), still it works with the following setting:
![image](https://user-images.githubusercontent.com/178714/32245411-fc44a604-be7b-11e7-9db0-7b916536b09f.png)

**Comment by duckbyte** [comment]
I think I know the issue....`OpenInTerminal` is not the same as `OpenTerminalHere`. That's a different plugin!

**Comment by duckbyte** [comment]
https://github.com/luktom/OpenInTerminal

**Comment by mx1up** [comment]
lol, you're right, my bad! :) thanks for helping out

**Comment by hzio** [comment]
aha, `OpenInTerminal ` is not my plugin, and my plugin dosn't support manually configuration so far, why not fork me if you like it :) @emanns95 @mxttie @IlyaEremin
